### PR TITLE
Refactor overlapping and undecidable instances

### PR DESCRIPTION
**Pull request by hyperthunk**
Tighten up class constraints, introduce instances at declaration sites, rework tests. Also replaced a sleep with a getProcessInfo call in one of the tests.

### CODE REVIEW

**Comment by qnikst** [comment]
LGTM, though not sure if changing LogMessage in the same commit is a good thing..

**Comment by qnikst** [comment]
CI failed for 7.4.2, I suppose we should update CI and drop 7.4.2 check, keeping compatibility with more than 3 major GHC versions doesn't look good.

**Comment by hyperthunk** [comment]
@qnikst - I fully plan to remove 7.4.\* support from all the platform libraries. I believe the build failure will go away once #6 is merged also. When that's done (hopefully later today), I'll rebase master into this branch and update the PR.

**Comment by hyperthunk** [comment]
> not sure if changing LogMessage in the same commit is a good thing

That was a bit lazy of me, yes. I can pull it out into a separate commit, in fact it was done separately locally, but I squashed the commits before pushing. I don't like commits that don't compile...

**Comment by qnikst** [comment]
I see. When choosing between commits that doesn't compile and commits that do not make separate changes, I prefer former, as it will allow bisecting at least.

**Pull request merged**
