### PR TITLE
Set travis to use stack and HEAD versions of cloud haskell dependencies

### PR DESCRIPTION
**Pull request by hyperthunk**
Maybe merge this before #5, and rebase with master? That way we'll get travis to confirm that #5 is good to merge.

### CODE REVIEW

**Comment by facundominguez** [comment]
I think travis.yaml should be stack.yaml.

**Comment by hyperthunk** [comment]
> I think travis.yaml should be stack.yaml.

Will that not mess with stack being run from the top level? But if you think that's better, I'll rename it.

**Comment by facundominguez** [comment]
d-p has a stack.yaml file as well. Haven't seen interference of the sort with it.

**Comment by qnikst** [comment]
If we are using stack for building this project we should install that like http://docs.haskellstack.org/en/stable/install_and_upgrade/#ubuntu . Or search on a github, as I expect this problem is already solved by other users.

**Comment by hyperthunk** [comment]
@qnikst - I copied the recipe for installing stack from distributed-process, so I'm assuming what I've put in here works just fine.

**Comment by hyperthunk** [comment]
@facundominguez - yeah okay, I'll rename it and update.

**Comment by qnikst** [comment]
@hyperthunk my comment was based on:

```
$ stack test --stack-yaml=travis.yaml

/home/travis/build.sh: line 45: stack: command not found

The command "stack test --stack-yaml=travis.yaml" exited with 127.
```

**Comment by hyperthunk** [comment]
@qnikst I see, sure we can copy https://github.com/haskell-distributed/cloud-haskell/blob/master/.travis.yml though...

**Comment by hyperthunk** [comment]
So, this branch clearly fixes travis! @facundominguez @qnikst - Are we happy with the file names and vi config changes? If so I'm going to merge.

**Comment by hyperthunk** [comment]
Okay, actually all the checks have passed, so I'm going to merge.

**Comment by qnikst** [comment]
First time `curl` failed so I have triggered rebuild. So it seems that we may experience sporadic test failures because of CI.

**Comment by hyperthunk** [comment]
> First time curl failed so I have triggered rebuild. So it seems that we may experience sporadic test failures because of CI.

Yeah, I guess so. I've set up a bot for https://haskell-distributed.slack.com - so I'll keep an eye on these. I don't think there's much we can do if travis is unable to grab stack reliably. :/

**Comment by hyperthunk** [comment]
Note that I'm playing around with coverage, so the build may be broken until I resolve that.

**Comment by mboes** [comment]
Just a note that the `stack.yaml` in this PR essentially destroys build reproducibility. But not just for Travis - end users too (anyone using Stack). `HEAD` is indeed accepted as a valid `commit:` value but only because Stack doesn't want to be parsing refspecs itself, and wants to allow passing in an immutable tag. It passes on the value of that field to Git unchecked, even if it's not a SHA1 hash. You're not meant to pass in a mutable symbolic ref such as HEAD: the docs say [that is likely to cause problems](http://docs.haskellstack.org/en/stable/yaml_configuration/#packages).

For the `distributed-process` package, we moved away from building against HEAD versions. If that's really what we need to be building against day-to-day, then it means release cycles of packages aren't in fact independent, so maintaining all this as separate packages in separate repos with separate versions and separate release cycles is probably not a good idea.

**Comment by hyperthunk** [comment]
I totally agree @mboes - this is a temporary situation while I get adjusted to the exception handling changes in distributed-process. I plan to fix on specific commits over be next couple of days, once I've decided which point at which in the commit history to depend on distributed-process makes sense. Post 0.6 but not HEAD.

**Comment by mboes** [comment]
Cool. That plan sounds great. Should @facundominguez just cut a new minor distributed-process release including the exceptions stuff? Minor releases are cheap these days with `stack upload`.

**Comment by hyperthunk** [comment]
A new minor release is the way to go, yeah, but maybe wait and see if some of the other PRs land soon as well? In particular id like to fix tracing (which is simple I think) before we do that. Maybe in a week or so?

**Comment by mboes** [comment]
> Maybe in a week or so?

Is there a point to batching? :)

Since we review and test patches _before_ merging, cutting a new minor release should involve nothing more than `stack upload` to Hackage and double checking of the `ChangeLog`. You should feel free to request one even for a single feature, and expect to see it happen in the next few hours or a day.

**Comment by hyperthunk** [comment]
Okay cool, we I'm happy to start relying on a new minor asap and ask for another one as soon as I've fixed the tracing. :)

**Comment by facundominguez** [comment]
0.6.1 uploaded.

**Pull request merged**
